services:
  postgres:
    container_name: link_fetcher_postgres
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: link_fetcher